# Generated by Django 3.2 on 2022-11-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletotag',
            options={'verbose_name_plural': '文章标签'},
        ),
        migrations.AlterModelTable(
            name='articletotag',
            table='ArticleToTag',
        ),
    ]
