# Generated by Django 3.2 on 2022-11-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20221105_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='site_theme',
            field=models.CharField(max_length=64, null=True, verbose_name='站点样式'),
        ),
    ]
