# Generated by Django 3.2 on 2022-11-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_userinfo_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletotag',
            options={'verbose_name_plural': '文章与标签'},
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
